[H2 Today]
title = "H2 VIEW — Recent posts"
url = "https://www.h2-view.com/news/all-news/"
entrySelector = ".story-list-article"
titleSelector = "h3"
linkSelector = "h3 a"

[wikivoyage]
title = "Wikivoyage recommendations"
url = "https://en.wikivoyage.org/wiki/Main_Page"
entrySelector = ".jcarousel-wrapper .jcarousel-item"
titleSelector = "h2"
linkSelector = "h2 a"
